version: '3.4'

networks:
  demotodoapp:
    driver: bridge

services:
  demoappdb:
    container_name: demoappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      SA_PASSWORD: "HashPassword123!"
      ACCEPT_EULA: "Y"
    networks:
        - demotodoapp
  todoapi:
    container_name: todoapi
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: ToDoAPI/Dockerfile
    ports:
        - 8001:80
    depends_on:
        - demoappdb
    environment:
        - DB_HOST=demoappdb
        - DB_NAME=ToDoDB
        - DB_SA_PASSWORD=HashPassword123!
    networks:
        - demotodoapp
        

